//This code was generated by a tool.
//Changes to this file will be lost if the code is regenerated.
// See the blog post here for help on using the generated code: http://erikej.blogspot.dk/2014/10/database-first-with-sqlite-in-universal.html
using System;
using System.Data.SQLite;

namespace Model
{
    public class SQLiteDb
    {
        string _path;
        public SQLiteDb(string path)
        {
            _path = path;
        }

        // Substitua o método Create para criar as tabelas manualmente, pois SQLiteConnection não possui CreateTable.
        // Use comandos SQL para criar as tabelas AGENDAMENTO e VEICULO.

        public void Create()
        {
            using (var db = new SQLiteConnection(_path))
            {
                db.Open();
                using (var cmd = db.CreateCommand())
                {
                    cmd.CommandText = @"
                        CREATE TABLE IF NOT EXISTS AGENDAMENTO (
                            USUARIO TEXT,
                            NOME TEXT,
                            EMPRESA TEXT,
                            DATAHORA TEXT,
                            field5 TEXT
                        );
                        CREATE TABLE IF NOT EXISTS VEICULO (
                            CPF TEXT,
                            NOME TEXT,
                            CPFAJUDANTE TEXT,
                            NOMEAJUDANTE TEXT,
                            DATAHORA TEXT,
                            PLACA TEXT,
                            TIPOVEICULO TEXT,
                            PRESTADOR TEXT,
                            AGREGADO TEXT,
                            EMPRESA TEXT,
                            CELULAR TEXT
                        );
                    ";
                    cmd.ExecuteNonQuery();
                }
            }
        }
    }
    public partial class AGENDAMENTO
    {
        public String USUARIO { get; set; }
        
        public String NOME { get; set; }
        
        public String EMPRESA { get; set; }
        
        public String DATAHORA { get; set; }
        
        public String field5 { get; set; }
        
    }
    
    public partial class VEICULO
    {
        public String CPF { get; set; }
        
        public String NOME { get; set; }
        
        public String CPFAJUDANTE { get; set; }
        
        public String NOMEAJUDANTE { get; set; }
        
        public String DATAHORA { get; set; }
        
        public String PLACA { get; set; }
        
        public String TIPOVEICULO { get; set; }
        
        public String PRESTADOR { get; set; }
        
        public String AGREGADO { get; set; }
        
        public String EMPRESA { get; set; }
        
        public String CELULAR { get; set; }
        
    }
    
}
